"""Reference adapter — Apache HttpClient + TestNG + org.json (build-your-own framework style).

Two layers: hand-written scaffolding (RestClient/TestBase, stable, see examples/output) and
the GENERATED test layer below. You don't regenerate your framework; you regenerate tests.
"""
import json


def to_apache_testng(package, verdict, well_formed, class_name="RefundCancellationApiTest"):
    L = [
        "import com.qa.base.TestBase;",
        "import com.qa.client.RestClient;",
        "import org.apache.http.client.methods.CloseableHttpResponse;",
        "import org.apache.http.util.EntityUtils;",
        "import org.json.JSONObject;",
        "import org.testng.Assert;",
        "import org.testng.annotations.BeforeMethod;",
        "import org.testng.annotations.Test;",
        "",
        "import java.util.HashMap;",
        "",
        "// Auto-generated by AeroAssist QA framework - Apache HttpClient + TestNG adapter (reference)",
        "// TEST layer only. RestClient/TestBase are hand-written framework scaffolding.",
        f"public class {class_name} extends TestBase {{",
        "",
        "    RestClient restClient;",
        '    String cancelUrl = "/cancel";',
        "",
        "    @BeforeMethod",
        "    public void setUp() {",
        "        restClient = new RestClient();",
        "    }",
        "",
    ]
    for r in package["data"]:
        rid = r["id"]
        body = json.dumps({k: r.get(k) for k in
                           ("pnr", "booking_time", "cancel_time", "amount", "payment_status")})
        body_java = body.replace('"', '\\"')
        L += [
            "    @Test",
            f"    public void cancel_{rid}() throws Exception {{   // category: {r.get('category')}",
            "        HashMap<String, String> headers = new HashMap<>();",
            '        headers.put("Content-Type", "application/json");',
            f'        String body = "{body_java}";',
            "        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);",
            "        int statusCode = response.getStatusLine().getStatusCode();",
        ]
        if not well_formed(r):
            L += ["        Assert.assertEquals(statusCode, 422);   // malformed input rejected"]
        else:
            L += [
                "        Assert.assertEquals(statusCode, 200);",
                '        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");',
                "        JSONObject responseJson = new JSONObject(responseString);",
                f'        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), {str(verdict(r)).lower()});',
            ]
        L += ["    }", ""]
    L.append("}")
    return "\n".join(L)


REST_CLIENT_STUB = '''package com.qa.client;

import org.apache.http.client.methods.*;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import com.qa.base.TestBase;
import java.util.HashMap;

// Hand-written framework layer - wraps Apache HttpClient. Stable; not regenerated.
public class RestClient {
    public CloseableHttpResponse post(String url, String body, HashMap<String,String> headers) throws Exception {
        CloseableHttpClient client = HttpClients.createDefault();
        HttpPost post = new HttpPost(TestBase.BASE_URL + url);
        for (var e : headers.entrySet()) post.addHeader(e.getKey(), e.getValue());
        post.setEntity(new StringEntity(body));
        return client.execute(post);
    }
    public CloseableHttpResponse get(String url) throws Exception {
        CloseableHttpClient client = HttpClients.createDefault();
        return client.execute(new HttpGet(TestBase.BASE_URL + url));
    }
}
'''

TEST_BASE_STUB = '''package com.qa.base;

// Hand-written framework layer - config/base. Stable; not regenerated.
public class TestBase {
    public static final String BASE_URL = "http://localhost:8000"; // point at the real service
}
'''
