"""Reference adapter — Playwright (UI, JavaScript). Covers the UI layer.

Prototyped Day 10; live browser-run parked for a containerized environment.
"""


def to_playwright(package, verdict, well_formed):
    L = [
        "// Auto-generated by AeroAssist QA framework - Playwright adapter (reference)",
        "// UI layer. Prototyped early; live browser-run parked for a containerized env.",
        "const { test, expect } = require('@playwright/test');",
        "",
        "test.describe('Booking cancellation refund (UI)', () => {",
        "",
    ]
    for r in package["data"]:
        rid = r["id"]
        L += [
            f"  test('cancel {rid} - {r.get('category')}', async ({{ page }}) => {{",
            f"    await page.goto('/booking/{r.get('pnr')}');",
            "    await page.getByRole('button', { name: 'Cancel booking' }).click();",
        ]
        if not well_formed(r):
            L += ["    await expect(page.getByText(/invalid|error/i)).toBeVisible();"]
        elif verdict(r):
            L += ["    await expect(page.getByText('Full refund issued')).toBeVisible();"]
        else:
            L += ["    await expect(page.getByText('No refund')).toBeVisible();"]
        L += ["  });", ""]
    L.append("});")
    return "\n".join(L)
