"""Reference adapter — REST Assured (Java, fluent given/when/then DSL).

Note: REST Assured's given/when/then is a fluent Java DSL (code), NOT Cucumber's Gherkin.
"""
import json


def to_rest_assured(package, verdict, well_formed, class_name="RefundCancellationTest"):
    L = [
        "import io.restassured.http.ContentType;",
        "import org.junit.jupiter.api.Test;",
        "import static io.restassured.RestAssured.given;",
        "import static org.hamcrest.Matchers.*;",
        "",
        "// Auto-generated by AeroAssist QA framework - REST Assured adapter (reference)",
        "// Source: the same framework-agnostic JSON that drives the runnable Python adapter.",
        f"public class {class_name} {{",
        "",
    ]
    for r in package["data"]:
        rid = r["id"]
        body = json.dumps({k: r.get(k) for k in
                           ("pnr", "booking_time", "cancel_time", "amount", "payment_status")})
        body_java = body.replace('"', '\\"')
        if not well_formed(r):
            status, then_body = 422, ""
        else:
            status = 200
            then_body = f'\n            .body("refund_allowed", equalTo({str(verdict(r)).lower()}))'
        L += [
            "    @Test",
            f"    void cancel_{rid}() {{   // category: {r.get('category')}",
            "        given()",
            "            .contentType(ContentType.JSON)",
            f'            .body("{body_java}")',
            "        .when()",
            '            .post("/cancel")',
            "        .then()",
            f"            .statusCode({status}){then_body};",
            "    }",
            "",
        ]
    L.append("}")
    return "\n".join(L)
