import com.qa.base.TestBase;
import com.qa.client.RestClient;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.util.EntityUtils;
import org.json.JSONObject;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.HashMap;

// Auto-generated by AeroAssist QA framework - Apache HttpClient + TestNG adapter (reference)
// TEST layer only. RestClient/TestBase are hand-written framework scaffolding.
public class RefundCancellationApiTest extends TestBase {

    RestClient restClient;
    String cancelUrl = "/cancel";

    @BeforeMethod
    public void setUp() {
        restClient = new RestClient();
    }

    @Test
    public void cancel_R01() throws Exception {   // category: valid
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"ABC123\", \"booking_time\": \"2026-01-15T10:00:00Z\", \"cancel_time\": \"2026-01-15T18:00:00Z\", \"amount\": 250.0, \"payment_status\": \"active\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 200);
        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");
        JSONObject responseJson = new JSONObject(responseString);
        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), true);
    }

    @Test
    public void cancel_R02() throws Exception {   // category: valid
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"QWE456\", \"booking_time\": \"2026-01-14T08:00:00Z\", \"cancel_time\": \"2026-01-16T09:00:00Z\", \"amount\": 175.5, \"payment_status\": \"active\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 200);
        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");
        JSONObject responseJson = new JSONObject(responseString);
        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), false);
    }

    @Test
    public void cancel_R03() throws Exception {   // category: edge
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"RTY789\", \"booking_time\": \"2026-01-10T00:00:00Z\", \"cancel_time\": \"2026-01-11T00:00:00Z\", \"amount\": 99.99, \"payment_status\": \"active\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 200);
        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");
        JSONObject responseJson = new JSONObject(responseString);
        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), true);
    }

    @Test
    public void cancel_R04() throws Exception {   // category: edge
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"XYZ789\", \"booking_time\": \"2026-01-12T12:00:00Z\", \"cancel_time\": \"2026-01-12T20:00:00Z\", \"amount\": 175.5, \"payment_status\": \"refunded\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 200);
        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");
        JSONObject responseJson = new JSONObject(responseString);
        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), false);
    }

    @Test
    public void cancel_R05() throws Exception {   // category: edge
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"UIO234\", \"booking_time\": \"2026-01-20T23:30:00Z\", \"cancel_time\": \"2026-01-21T00:15:00Z\", \"amount\": 512.0, \"payment_status\": \"active\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 200);
        String responseString = EntityUtils.toString(response.getEntity(), "UTF-8");
        JSONObject responseJson = new JSONObject(responseString);
        Assert.assertEquals(responseJson.getBoolean("refund_allowed"), true);
    }

    @Test
    public void cancel_R06() throws Exception {   // category: adversarial
        HashMap<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        String body = "{\"pnr\": \"PAS567\", \"booking_time\": \"2026-01-05T09:45:00Z\", \"cancel_time\": null, \"amount\": 0.0, \"payment_status\": \"confirmed\"}";
        CloseableHttpResponse response = restClient.post(cancelUrl, body, headers);
        int statusCode = response.getStatusLine().getStatusCode();
        Assert.assertEquals(statusCode, 422);   // malformed input rejected
    }

}