import io.restassured.http.ContentType;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

// Auto-generated by AeroAssist QA framework - REST Assured adapter (reference)
// Source: the same framework-agnostic JSON that drives the runnable Python adapter.
public class RefundCancellationTest {

    @Test
    void cancel_R01() {   // category: valid
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"ABC123\", \"booking_time\": \"2026-01-15T10:00:00Z\", \"cancel_time\": \"2026-01-15T18:00:00Z\", \"amount\": 250.0, \"payment_status\": \"active\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(200)
            .body("refund_allowed", equalTo(true));
    }

    @Test
    void cancel_R02() {   // category: valid
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"QWE456\", \"booking_time\": \"2026-01-14T08:00:00Z\", \"cancel_time\": \"2026-01-16T09:00:00Z\", \"amount\": 175.5, \"payment_status\": \"active\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(200)
            .body("refund_allowed", equalTo(false));
    }

    @Test
    void cancel_R03() {   // category: edge
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"RTY789\", \"booking_time\": \"2026-01-10T00:00:00Z\", \"cancel_time\": \"2026-01-11T00:00:00Z\", \"amount\": 99.99, \"payment_status\": \"active\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(200)
            .body("refund_allowed", equalTo(true));
    }

    @Test
    void cancel_R04() {   // category: edge
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"XYZ789\", \"booking_time\": \"2026-01-12T12:00:00Z\", \"cancel_time\": \"2026-01-12T20:00:00Z\", \"amount\": 175.5, \"payment_status\": \"refunded\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(200)
            .body("refund_allowed", equalTo(false));
    }

    @Test
    void cancel_R05() {   // category: edge
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"UIO234\", \"booking_time\": \"2026-01-20T23:30:00Z\", \"cancel_time\": \"2026-01-21T00:15:00Z\", \"amount\": 512.0, \"payment_status\": \"active\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(200)
            .body("refund_allowed", equalTo(true));
    }

    @Test
    void cancel_R06() {   // category: adversarial
        given()
            .contentType(ContentType.JSON)
            .body("{\"pnr\": \"PAS567\", \"booking_time\": \"2026-01-05T09:45:00Z\", \"cancel_time\": null, \"amount\": 0.0, \"payment_status\": \"confirmed\"}")
        .when()
            .post("/cancel")
        .then()
            .statusCode(422);
    }

}